### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-elasticbeanstalk-cron.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "foxxmd/laravel-elasticbeanstalk-cron": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by MichaelHoughton** [comment]
This would be great to see - please let me know if you need help with this.

**Comment by MbahDjoe** [comment]
> This would be great to see - please let me know if you need help with this.

I haven't use Laravel 9 yet so I can't really test it, so would be great if someone can test using Laravel 9 and confirm it.
After checking the upgrade guide of Laravel I think it should be working fine.
Further I'll prefer to still support previous Laravel versions, so the version constraint should be `5 - 9` instead.

**Comment by MbahDjoe** [comment]
closed since I've created and tested new PR for Laravel 9 support #28

**Pull request closed without merging**
