### PR TITLE
Added Config

### PR DESCRIPTION
**Pull request by ghost**
Update to use the config files for a number of settings. Allowed for overwriting of environment variables. 

Should be backwards compatible but allow for more flexible deployments. 

The main feature added is the ability to change the path to `artisan`. Our deployments have `artisan` in a sub directory.

### CODE REVIEW

**Comment by Jono20201** [comment]
Looks good. I don't know what @FoxxMD thinks but I try to avoid using `private` unless its really needed, and prefer to use `protected`. Additionally the `protected $ecClient` property can now be removed?

**Comment by FoxxMD** [comment]
I agree with @Jono20201.

@linchpinstudios please make `$config` `protected` and remove `$ecClient` and then I'll merge 👍

Thanks for the contribution!

**Comment by linchpinstudios** [comment]
@Jono20201 @FoxxMD Thanks for the feedback, I've pushed those changes.

**Comment by Jono20201** [comment]
Thanks @linchpinstudios.

**Pull request merged**
